### PR TITLE
fix: Fix the vertical size calculation & the zoom on layer disable

### LINKED ISSUE #465: [Bug]:Zoom on main editor fail on disable layer
### Package Version

9.9.0

### Flutter Version

3.29

### Platforms

Android, iOS

### How to reproduce?

on mobile if zoom is enable, and the layers disable.
the main editor cant zoom because the double tap and the pinch will interacts with the layers ( doing nothing but absorbing the gesture)

The issue comes because the rotation and the scale is not in the Gesture so is not translucent
Image

### LINKED ISSUE #467: [Bug]: Extra SafeArea in PaintEditor
### Package Version

9.9.0

### Flutter Version

3,29

### Platforms

Android

### How to reproduce?

@hm21 I think I finally found the SafeArea that is messing in PaintEditor
inside `_buildBody` there is a SafeArea with no parameters and `_buildBody` is inside of  the SafeArea that contains the PaintEditorConfigSafeArea

Image

creating this scenario

this is with PaintEditor EditorSafeArea(bottom:false) with no changes  in the  `_buildBody` 
notice the padding at bottom

Image

and this the same case but without the SafeArea in `_buildBody` 

Image

will include this change in the #464

### PR DESCRIPTION
**Pull request by oscarshaitan**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/hm21/pro_image_editor/blob/stable/CONTRIBUTING.md#style-guides
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #465 #467

## What is the new behavior?
refactor: replace getMinimumSize with getValidSizeOrDefault in various editors
fix: add `forceIgnoreGestures` to allow zoom gestures when a layer is disable

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: lib/shared/widgets/layer/interaction_helper/layer_interaction_helper_widget.dart [hunk 1]
```diff
@@ -175,7 +183,8 @@ class _LayerInteractionHelperWidgetState
 
     return TooltipVisibility(
       visible: layerInteraction.style.showTooltips,
-      child: DeferPointer(
+      child: IgnorePointer(
```
Comment (hm21) [inline lib/shared/widgets/layer/interaction_helper/layer_interaction_helper_widget.dart]: The `DeferPointer` widget is everywhere mandatory, without it, gesture detection won't work correctly anymore. For example, if you draw a long vertical line which you later rotate 45deg and then try to select it at the ends, it won’t work without `DeferPointer`.

File: lib/designs/grounded/widgets/bottombar/grounded_filter_bar.dart [hunk 2]
```diff
@@ -1,10 +1,11 @@
 import 'package:flutter/material.dart';
-
+import 'package:pro_image_editor/core/utils/size_utils.dart';
```
Comment (hm21) [inline lib/designs/grounded/widgets/bottombar/grounded_filter_bar.dart]: Please update everywhere the import to use the relative path style: `import '/core/utils/size_utils.dart';` for consistency.

File: lib/features/main_editor/main_editor.dart [hunk 3]
```diff
@@ -1311,23 +1311,22 @@ class ProImageEditorState extends State<ProImageEditor>
...
-                                .style.subEditorPage.enforceSizeFromMainEditor
-                            ? sizesManager.editorSize.height
-                            : null,
-                        clipBehavior: Clip.hardEdge,
-                        decoration: BoxDecoration(
-                          borderRadius: mainEditorConfigs
-                              .style.subEditorPage.borderRadius,
-                        ),
-                        child: page,
+                        child: Container(
```
Comment (hm21) [inline lib/features/main_editor/main_editor.dart]: This part can be removed, it only eliminates a comma without making any meaningful change.

**Review by hm21 — CHANGES_REQUESTED** [review]
Thanks for creating the new PR! The main issue is the removal of `DeferPointer`, unfortunately that’s not possible, and I’ve explained why in the review.

As for the other changes, like renaming `getValidSizeOrDefault` and removing `SafeArea`, I can merge them once you've addressed the review comments there. 

Thanks for your collaboration! I appreciate your help on this.

File: lib/shared/widgets/layer/interaction_helper/layer_interaction_helper_widget.dart (hunk 1 above)
Comment (oscarshaitan) [reply lib/shared/widgets/layer/interaction_helper/layer_interaction_helper_widget.dart]: ok Im going to roll back that and add simply early return
```dart
 if (widget.forceIgnoreGestures) {
      return IgnorePointer(
          ignoring: widget.forceIgnoreGestures, child: widget.child);
    }
```

Comment (oscarshaitan) [reply lib/shared/widgets/layer/interaction_helper/layer_interaction_helper_widget.dart]: that will mix both solutions  preserving the behaviour you mention but also allowing to totally disable the layer

File: CHANGELOG.md [hunk 4]
```diff
@@ -1,5 +1,8 @@
 # Changelog
 
+## 9.9.3
+- **FIX**(Main-Editor & Paint-Editor): Fix the main editor size calculation to reduce layers shiftting and fix the disable layers not allowign zoom gestures on main editor
```
Comment (hm21) [inline CHANGELOG.md]:
```suggestion
- **FIX**(Layers): Corrected size calculation to prevent layer shifting.
- **FIX**(Main-Editor): Fixed an issue where disabled layers blocked zoom gestures.
```

File: lib/features/blur_editor/blur_editor.dart [hunk 5]
```diff
@@ -5,6 +5,7 @@ import 'dart:async';
 import 'package:flutter/foundation.dart';
 import 'package:flutter/material.dart';
 import 'package:flutter/services.dart';
+import 'package:pro_image_editor/core/utils/size_utils.dart';
```
Comment (hm21) [inline lib/features/blur_editor/blur_editor.dart]:
```suggestion
import '/core/utils/size_utils.dart';
```

File: lib/features/filter_editor/filter_editor.dart [hunk 6]
```diff
@@ -4,6 +4,7 @@ import 'dart:async';
 import 'package:flutter/foundation.dart';
 import 'package:flutter/material.dart';
 import 'package:flutter/services.dart';
+import 'package:pro_image_editor/core/utils/size_utils.dart';
```
Comment (hm21) [inline lib/features/filter_editor/filter_editor.dart]:
```suggestion
import '/core/utils/size_utils.dart';
```

File: lib/features/main_editor/widgets/main_editor_layers.dart [hunk 7]
```diff
@@ -1,5 +1,6 @@
 import 'package:flutter/material.dart';
 import 'package:flutter/services.dart';
+import 'package:pro_image_editor/core/utils/size_utils.dart';
```
Comment (hm21) [inline lib/features/main_editor/widgets/main_editor_layers.dart]:
```suggestion
import '/core/utils/size_utils.dart';
```

File: lib/features/tune_editor/tune_editor.dart [hunk 8]
```diff
@@ -4,6 +4,7 @@ import 'dart:async';
 import 'package:flutter/foundation.dart';
 import 'package:flutter/material.dart';
 import 'package:flutter/services.dart';
+import 'package:pro_image_editor/core/utils/size_utils.dart';
```
Comment (hm21) [inline lib/features/tune_editor/tune_editor.dart]:
```suggestion
import '/core/utils/size_utils.dart';
```

File: lib/shared/widgets/layer/layer_widget.dart [hunk 9]
```diff
@@ -298,6 +298,8 @@ class _LayerWidgetState extends State<LayerWidget>
       callbacks: callbacks,
       selected: widget.selected,
       onEditLayer: widget.onEditTap,
+      forceIgnoreGestures:
```
Comment (hm21) [inline lib/shared/widgets/layer/layer_widget.dart:301]: I'm not sure if that's going to be a problem. But if we use `IgnorePointer` every callback below, it might stop working too. I'm about 90% sure there won't be any issues with custom user logic, but i didn't test it. 
You mentioned before the only problem is with the double-tap interaction, right? What do you think about this approach: 
```suggestion
forceIgnoreGestures:
    !(interaction.enableSelection || interaction.enableEdit) &&
        configs.mainEditor.enableZoom &&
        configs.mainEditor.enableDoubleTapZoom,
```

If you're confident that no necessary callbacks will be blocked, you can ignore it, I'll still go ahead and merge it. I'll leave the decision up to you whether we should extend it or not.

**Review by hm21 — CHANGES_REQUESTED** [review]
Sorry, my bad, I didn't explain it clearly enough. I'd prefer if you could rename every import. This time, I’ve added a review comment to each one. Also, I’d appreciate it if we could separate the changelog messages.

I’ve added a small suggestion for `forceIgnoreGestures`, but feel free to ignore it if you think it’s not necessary.

Once that's done, I’ll go ahead and merge it right away. Thanks again for all the work and time you've put into improving the image editor!

File: lib/shared/widgets/layer/layer_widget.dart (hunk 9 above)
Comment (oscarshaitan) [reply lib/shared/widgets/layer/layer_widget.dart:301]: I didn't include those because the my idea was if layer interactions are disable allow everything else in the main editor like zoom on any gesture.

**Comment by oscarshaitan** [comment]
> Sorry, my bad, I didn't explain it clearly enough. I'd prefer if you could rename every import. This time, I’ve added a review comment to each one. Also, I’d appreciate it if we could separate the changelog messages.
> 
> I’ve added a small suggestion for `forceIgnoreGestures`, but feel free to ignore it if you think it’s not necessary.
> 
> Once that's done, I’ll go ahead and merge it right away. Thanks again for all the work and time you've put into improving the image editor!

for sure this library is awesome and is helping me build one hell of a cluster feature, so ill try all that I can do to make it better
